apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This is the main kustomization file that deploys the entire stack
# Use environment-specific overlays for different deployments

resources:
  - infrastructure/base
  - apps/base

# Common labels applied to all resources
labels:
  - includeSelectors: true
    pairs:
      managed-by: kustomize
      repository: k3s-install