apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  labels:
    app: cloudflared
data:
  config.yaml: |
    tunnel: my-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: "*.sotools.cc"
      service: http://traefik.kube-system.svc.cluster.local:80
    - service: http_status:404