apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/component: tunnel
      app.kubernetes.io/part-of: infrastructure

namespace: cloudflared