apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: cloudflared
  app.kubernetes.io/component: tunnel
  app.kubernetes.io/part-of: infrastructure

namespace: cloudflared