apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: whoami-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: whoami
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: uptime-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: uptime