apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  template:
    spec:
      containers:
      - name: whoami
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime
spec:
  template:
    spec:
      containers:
      - name: uptime
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi