apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: uptime
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: k3s-apps

namespace: apps