apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    purpose: applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  labels:
    name: cloudflared
    purpose: cloudflare-tunnel